In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4,5,6],[2,3,4,5,6]])
print(a)

[list([1, 2, 3, 4, 5, 6]) list([2, 3, 4, 5, 6])]


In [3]:
b=np.ones((4,5),dtype=np.int64)
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
c=np.zeros((4,5),dtype=np.int64)
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
e=np.zeros((4,5),dtype=np.double)
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
e=np.zeros((4,5),dtype=np.float)
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
d=np.arange(4,100,2)
print(d)

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [8]:
d=np.arange(4,100)
print(d)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [9]:
d=np.arange(0,100,3)
print(d)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [10]:
d=np.arange(100)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [12]:
e=np.concatenate([b,c])
e

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [13]:
e=d.astype(np.float)
print(e)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [50]:
e=d.astype(np.int)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [14]:
d=np.random.random((50,100))
print(d)

[[1.99057903e-03 8.96710242e-01 5.56969282e-01 ... 9.38937940e-01
  2.78311892e-04 2.10186321e-01]
 [8.27414567e-01 7.02591525e-01 9.62758611e-01 ... 6.47722556e-01
  4.16969132e-01 6.68633083e-01]
 [4.78993607e-01 7.16329975e-01 1.97952792e-01 ... 3.07572749e-01
  6.40796963e-01 4.81824567e-01]
 ...
 [4.49255058e-01 9.30669731e-02 9.44409890e-02 ... 3.34435556e-01
  5.52049159e-02 9.50767867e-01]
 [1.70261291e-01 7.32850571e-02 2.84120479e-01 ... 4.42776361e-01
  1.00296635e-02 6.36869119e-02]
 [8.12654052e-01 3.52920729e-01 6.12869248e-01 ... 4.31349560e-01
  9.73629686e-01 1.15115821e-01]]


# shaping

In [52]:
h=np.random.random((3,4))
j=h.reshape(4,3)
print(h)
print()
print(j)

[[0.7763434  0.9093502  0.00444543 0.99185818]
 [0.93030778 0.92269845 0.48595145 0.01563255]
 [0.55844223 0.31676624 0.60299032 0.95315321]]

[[0.7763434  0.9093502  0.00444543]
 [0.99185818 0.93030778 0.92269845]
 [0.48595145 0.01563255 0.55844223]
 [0.31676624 0.60299032 0.95315321]]


In [53]:
h=np.random.random((3,4))
j=h.reshape(12,1)
print(h)
print()
print(j)

[[0.50096423 0.50463613 0.14702192 0.7737415 ]
 [0.13592141 0.27876727 0.51449619 0.92954669]
 [0.18778057 0.27069896 0.87387344 0.33146414]]

[[0.50096423]
 [0.50463613]
 [0.14702192]
 [0.7737415 ]
 [0.13592141]
 [0.27876727]
 [0.51449619]
 [0.92954669]
 [0.18778057]
 [0.27069896]
 [0.87387344]
 [0.33146414]]


In [54]:
a=[1,2,3,4,5,6,2,3,4,5,6]

In [55]:
a=np.array([[1,2,3,4,5,6],[3,4,5,6,7,8]])
a

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]])

In [56]:
a.transpose()

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6],
       [5, 7],
       [6, 8]])

In [57]:
x=np.arange(4)
x1=x.reshape((2,2))
x

array([0, 1, 2, 3])

In [58]:
x1.transpose()

array([[0, 2],
       [1, 3]])

In [59]:
x=np.arange(4)
x


array([0, 1, 2, 3])

In [60]:
x1=x.reshape((2,2))
x1.transpose()

array([[0, 2],
       [1, 3]])

In [18]:
x=np.random.random((10,4))
x

array([[0.35809457, 0.99559404, 0.94946151, 0.06007023],
       [0.26971249, 0.29842568, 0.04652664, 0.57553522],
       [0.24815562, 0.89958735, 0.75698287, 0.50894479],
       [0.56819876, 0.52633757, 0.63535969, 0.75494899],
       [0.41901348, 0.54030663, 0.47036798, 0.35477619],
       [0.85140276, 0.72704175, 0.99496798, 0.28609172],
       [0.2218236 , 0.43301892, 0.01081274, 0.74570064],
       [0.59275288, 0.95918248, 0.78692333, 0.13293706],
       [0.56541035, 0.5332933 , 0.16592953, 0.38324102],
       [0.77378265, 0.96565263, 0.43726295, 0.35510424]])

In [21]:
m=x.reshape(4,10)
m.transpose()

array([[0.35809457, 0.75698287, 0.85140276, 0.78692333],
       [0.99559404, 0.50894479, 0.72704175, 0.13293706],
       [0.94946151, 0.56819876, 0.99496798, 0.56541035],
       [0.06007023, 0.52633757, 0.28609172, 0.5332933 ],
       [0.26971249, 0.63535969, 0.2218236 , 0.16592953],
       [0.29842568, 0.75494899, 0.43301892, 0.38324102],
       [0.04652664, 0.41901348, 0.01081274, 0.77378265],
       [0.57553522, 0.54030663, 0.74570064, 0.96565263],
       [0.24815562, 0.47036798, 0.59275288, 0.43726295],
       [0.89958735, 0.35477619, 0.95918248, 0.35510424]])

In [23]:
np.random.randint(0,100,(6,6))


array([[50, 99, 98, 97, 51, 16],
       [12,  3,  1, 49,  0, 70],
       [94, 54, 25, 84,  4, 91],
       [20, 29, 59, 18,  1, 43],
       [86, 93, 73, 98, 35, 34],
       [ 1, 34, 47, 92, 74, 12]])

In [24]:
np.random.randint(100,200,(6,6))

array([[129, 158, 152, 131, 132, 112],
       [112, 177, 142, 131, 146, 174],
       [113, 181, 142, 180, 188, 116],
       [110, 148, 140, 179, 194, 144],
       [188, 182, 128, 123, 109, 181],
       [184, 112, 123, 171, 135, 155]])

In [65]:
#a=np.random.randint(0,100,(6,6))
#np.random.randint(100,200,(6,6))
#np.savez("file.npz",a,b)

In [68]:
data=np.load("file.npz")

In [69]:
type(data)

numpy.lib.npyio.NpzFile

In [94]:
x=data.files
x

['a', 'b']

In [96]:
x=data['a']
x

array([[79, 50, 32, 14,  3, 87, 69,  6, 95, 33],
       [94, 93, 20, 78, 56, 97, 91, 63, 91, 25],
       [74, 47, 69, 57, 61, 12, 36, 62, 49,  3],
       [79, 65, 85, 86, 42, 89, 18, 98, 56, 60],
       [42, 54,  9, 63, 97, 95, 45, 94, 50, 71],
       [14, 92, 35, 88, 70, 94, 73, 24, 52, 20],
       [50, 79,  2, 18, 67, 64, 35, 98, 66, 42],
       [76, 86, 45, 15, 14, 37, 53, 19, 66, 20],
       [23, 33, 23, 59,  8, 92, 45,  9, 36, 71],
       [77, 64, 71, 87, 47, 80, 14, 67, 82, 31]])

In [78]:
data.files

['arr_0', 'arr_1']

In [80]:
x=data['arr_1']
x

array([[13859, 15017, 17006, ..., 10629, 16014, 11020],
       [14782, 19130, 19351, ..., 13102, 17265, 15239],
       [19905, 17250, 14000, ..., 10578, 15207, 18633],
       ...,
       [16893, 19868, 14842, ..., 11658, 11305, 16852],
       [10693, 18172, 13731, ..., 12148, 11535, 18659],
       [15384, 14718, 16331, ..., 16372, 10189, 13615]])

In [25]:
a=np.random.randint(0,1000,(1000,1000))
b=np.random.randint(10000,20000,(1000,1000))
np.savez('file.npz',a,b)

In [82]:
np.savez_compressed('file1.npz',a,b)

In [83]:
data=np.load("file.npz")
data

In [84]:
data=np.load("file1.npz")
data

In [85]:
v=data['arr_1']
v

array([[18512, 13524, 12251, ..., 17652, 19172, 17808],
       [13881, 13554, 15750, ..., 10880, 13773, 14428],
       [11778, 14149, 14910, ..., 19281, 18259, 13752],
       ...,
       [19406, 10783, 17488, ..., 15859, 17546, 18642],
       [13498, 12803, 12225, ..., 17885, 18495, 17551],
       [10230, 14666, 10039, ..., 12283, 14527, 11852]])

In [88]:
a=np.random.randint(0,100,(10,10))
b=np.random.randint(100,200,(10,10))
np.savez('file2.npz',a=a,b=b)
data=np.load('file2.npz')
print(data.files)

['a', 'b']


In [90]:
x=data['a']
x

array([[79, 50, 32, 14,  3, 87, 69,  6, 95, 33],
       [94, 93, 20, 78, 56, 97, 91, 63, 91, 25],
       [74, 47, 69, 57, 61, 12, 36, 62, 49,  3],
       [79, 65, 85, 86, 42, 89, 18, 98, 56, 60],
       [42, 54,  9, 63, 97, 95, 45, 94, 50, 71],
       [14, 92, 35, 88, 70, 94, 73, 24, 52, 20],
       [50, 79,  2, 18, 67, 64, 35, 98, 66, 42],
       [76, 86, 45, 15, 14, 37, 53, 19, 66, 20],
       [23, 33, 23, 59,  8, 92, 45,  9, 36, 71],
       [77, 64, 71, 87, 47, 80, 14, 67, 82, 31]])