# map function

In [1]:
def add(m,n):
    return m+n

In [2]:
l1=[1,2,3,4,5]
l2=[1,2,4,5,6]

In [3]:
list(map(add,(l1),(l2)))

[2, 4, 7, 9, 11]

In [18]:
def addition(n):
    return n+n

In [19]:
n=[1,2,3,4,5]

In [20]:
a=map(addition,(n))

In [21]:
print(list(a))

[2, 4, 6, 8, 10]


In [1]:
def force(m,a):
    return m*a

In [64]:
m=[10]
a=[100]

In [69]:
f=map(force,(m),(a))
print(list(f))

[1000]


In [100]:
def force1(m,a):
    print(a)
    print(b)
    str=a+b
    return str

In [101]:
p="python"
n="advance program"
print(str(map(force,p,n)))

In [87]:
f=lambda a,b:a*b
print(f(10,20))

200


In [92]:
f=lambda a:a**2
f(100)

10000

In [94]:
f=lambda a:a*a
f(100)

10000

In [99]:
f=lambda m,a:m*a
print(f(10,100))

1000


# numpyspace

In [3]:
import numpy as np


In [4]:
a=np.linspace(start=1,stop=100,num=5)
print(a)

[  1.    25.75  50.5   75.25 100.  ]


In [5]:
b=np.linspace(0,1,5)
b

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
a=np.array[1,2,3,4,5]
b=np.array[6,7,8,9,10]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [129]:
c=np.hstack((a,b))
d=np.vstack((a,b))

In [130]:
print("new array",c)
print("new array",d)

new array [  1.    25.75  50.5   75.25 100.     0.     0.25   0.5    0.75   1.  ]
new array [[  1.    25.75  50.5   75.25 100.  ]
 [  0.     0.25   0.5    0.75   1.  ]]


# numpy builton function

# eye function

In [170]:
a = np.eye(2, 1)
print("Matrix : \n", a)
b = np.eye(2, 3)
print("matrix :",b)

Matrix : 
 [[1.]
 [0.]]
matrix : [[0. 1. 0.]
 [0. 0. 1.]]


In [149]:
a=np.array([1,2,3,4])

array([1, 2, 3, 4])

In [155]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [158]:
b=np.array([[0.,  1.,  0.],
       [0.,  0.,  1.],
       [0.,  0.,  0.]])
np.eye(1, 2)


array([[1., 0.]])

# daignal function

In [164]:
np.diag(a,1)

array([0.])

In [167]:
np.diag(b,2)

array([0.])

# repeat function

In [119]:
np.repeat(3,5)

array([3, 3, 3, 3, 3])