In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

In [13]:
iris = load_iris()

In [14]:
X = iris.data
y =iris.target

In [15]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
feature_names = iris.feature_names
target_names = iris.target_names

In [18]:
print("Feature names:", feature_names)
print("Target names:", target_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [19]:
print("\nType of X is:", type(X))


Type of X is: <class 'numpy.ndarray'>


In [20]:
print("Frist 5 rows of X:\n", X[:150])

Frist 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40)

In [22]:
knn = KNeighborsClassifier(n_neighbors=5)
#Train the model using the training sets
knn.fit(X_train, y_train)
#Predict the response for test dataset
print("Response for test dataset:")
y_pred = knn.predict(X_test)
print(y_pred)

Response for test dataset:
[1 2 2 0 0 2 2 2 0 2 0 0 2 0 0 2 2 1 0 0 0 2 1 2 2 2 0 1 1 1 2 1 0 2 2 1 1
 1 2 1 1 1 0 0 2 1 0 1 2 2 2 2 2 2 1 0 1 2 1 0]


In [23]:
print(y_test)

[1 2 2 0 0 2 2 2 0 2 0 0 2 0 0 2 2 1 0 0 0 2 1 2 1 2 0 1 1 1 2 1 0 2 2 1 1
 1 2 1 1 1 0 0 2 2 0 1 2 2 2 1 2 2 1 0 1 2 1 0]


In [24]:
X_test

array([[4.9, 2.4, 3.3, 1. ],
       [6.3, 2.5, 5. , 1.9],
       [7.7, 3. , 6.1, 2.3],
       [4.4, 3. , 1.3, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [7.1, 3. , 5.9, 2.1],
       [7.2, 3.6, 6.1, 2.5],
       [4.8, 3. , 1.4, 0.3],
       [6.2, 2.8, 4.8, 1.8],
       [5.2, 3.4, 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.8, 2.8, 5.1, 2.4],
       [5.4, 3.9, 1.7, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.4, 2.8, 5.6, 2.1],
       [6.4, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [6.7, 3. , 5. , 1.7],
       [6.7, 3.3, 5.7, 2.5],
       [5. , 3.5, 1.6, 0.6],
       [5.6, 3. , 4.1, 1.3],
       [5. , 2. , 3.5, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [6.5, 3.2, 5.1, 2. ],
       [5.7, 2.6, 3.5, 1. ],
       [4.4, 2.9, 1.4, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [5.8, 2