In [253]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [254]:
iris = pd.read_csv("imr.csv")
#dd = pd.read_csv("imr.csv")
iris=pd.DataFrame(iris)
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [255]:
iris = iris.drop('Id',axis=1)
X = iris.iloc[:, :-1].values
y = iris.iloc[:, 4].values

In [206]:
print(iris.head(10))

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa
7            5.0           3.4            1.5           0.2  Iris-setosa
8            4.4           2.9            1.4           0.2  Iris-setosa
9            4.9           3.1            1.5           0.1  Iris-setosa


In [207]:
#dd=dd.set_index("Id")
#dd

In [209]:
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [210]:
iris.tail(50)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
100            6.3           3.3            6.0           2.5  Iris-virginica
101            5.8           2.7            5.1           1.9  Iris-virginica
102            7.1           3.0            5.9           2.1  Iris-virginica
103            6.3           2.9            5.6           1.8  Iris-virginica
104            6.5           3.0            5.8           2.2  Iris-virginica
105            7.6           3.0            6.6           2.1  Iris-virginica
106            4.9           2.5            4.5           1.7  Iris-virginica
107            7.3           2.9            6.3           1.8  Iris-virginica
108            6.7           2.5            5.8           1.8  Iris-virginica
109            7.2           3.6            6.1           2.5  Iris-virginica
110            6.5           3.2            5.1           2.0  Iris-virginica
111            6.4           2.7            5.3           1.9  Iris-virginica
112            6.8           3.0            5.5           2.1  Iris-virginica
113            5.7           2.5            5.0           2.0  Iris-virginica
114            5.8           2.8            5.1           2.4  Iris-virginica
115            6.4           3.2            5.3           2.3  Iris-virginica
116            6.5           3.0            5.5           1.8  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
118            7.7           2.6            6.9           2.3  Iris-virginica
119            6.0           2.2            5.0           1.5  Iris-virginica
120            6.9           3.2            5.7           2.3  Iris-virginica
121            5.6           2.8            4.9           2.0  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
123            6.3           2.7            4.9           1.8  Iris-virginica
124            6.7           3.3            5.7           2.1  Iris-virginica
125            7.2           3.2            6.0           1.8  Iris-virginica
126            6.2           2.8            4.8           1.8  Iris-virginica
127            6.1           3.0            4.9           1.8  Iris-virginica
128            6.4           2.8            5.6           2.1  Iris-virginica
129            7.2           3.0            5.8           1.6  Iris-virginica
130            7.4           2.8            6.1           1.9  Iris-virginica
131            7.9           3.8            6.4           2.0  Iris-virginica
132            6.4           2.8            5.6           2.2  Iris-virginica
133            6.3           2.8            5.1           1.5  Iris-virginica
134            6.1           2.6            5.6           1.4  Iris-virginica
135            7.7           3.0            6.1           2.3  Iris-virginica
136            6.3           3.4            5.6           2.4  Iris-virginica
137            6.4           3.1            5.5           1.8  Iris-virginica
138            6.0           3.0            4.8           1.8  Iris-virginica
139            6.9           3.1            5.4           2.1  Iris-virginica
140            6.7           3.1            5.6           2.4  Iris-virginica
141            6.9           3.1            5.1           2.3  Iris-virginica
142            5.8           2.7            5.1           1.9  Iris-virginica
143            6.8           3.2            5.9           2.3  Iris-virginica
144            6.7           3.3            5.7           2.5  Iris-virginica
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

In [211]:
iris.shape

(150, 5)

In [212]:
iris.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [213]:
iris.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [155]:
dd.columns.values

array(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'], dtype=object)

In [214]:
iris=pd.DataFrame(iris)
iris

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [215]:
pd.isnull(iris).sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [216]:
iris.count()

SepalLengthCm    150
SepalWidthCm     150
PetalLengthCm    150
PetalWidthCm     150
Species          150
dtype: int64

In [217]:
iris.mean()

SepalLengthCm    5.843333
SepalWidthCm     3.054000
PetalLengthCm    3.758667
PetalWidthCm     1.198667
dtype: float64

In [218]:
np.mean(iris)

SepalLengthCm    5.843333
SepalWidthCm     3.054000
PetalLengthCm    3.758667
PetalWidthCm     1.198667
dtype: float64

In [219]:
iris.median()

SepalLengthCm    5.80
SepalWidthCm     3.00
PetalLengthCm    4.35
PetalWidthCm     1.30
dtype: float64

In [220]:
iris.std()

SepalLengthCm    0.828066
SepalWidthCm     0.433594
PetalLengthCm    1.764420
PetalWidthCm     0.763161
dtype: float64

In [221]:
iris.var()

SepalLengthCm    0.685694
SepalWidthCm     0.188004
PetalLengthCm    3.113179
PetalWidthCm     0.582414
dtype: float64

In [222]:
iris.mode()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0            5.0           3.0            1.5           0.2      Iris-setosa
1            NaN           NaN            NaN           NaN  Iris-versicolor
2            NaN           NaN            NaN           NaN   Iris-virginica

In [223]:
iris=np.vstack(iris)

In [224]:
iris

array([['SepalLengthCm'],
       ['SepalWidthCm'],
       ['PetalLengthCm'],
       ['PetalWidthCm'],
       ['Species']], dtype='<U13')

In [225]:
#X=np.array(['SepalLengthCm', 'SepalWidthCm',"PetalLengthCm","PetalWidthCm"])
#y=np.array(["Species"])

In [226]:
#print(X)

In [227]:
#print(y)

In [231]:
#Split arrays or matrices into random train and test subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print("\n70% train data:")
print(X_train)
print(y_train)


70% train data:
[[5.5 2.4 3.7 1. ]
 [5.5 4.2 1.4 0.2]
 [6.  2.7 5.1 1.6]
 [6.5 3.  5.2 2. ]
 [5.5 2.3 4.  1.3]
 [6.4 2.8 5.6 2.1]
 [6.4 3.1 5.5 1.8]
 [7.3 2.9 6.3 1.8]
 [5.2 2.7 3.9 1.4]
 [6.3 3.4 5.6 2.4]
 [6.5 3.2 5.1 2. ]
 [5.4 3.7 1.5 0.2]
 [4.7 3.2 1.6 0.2]
 [5.5 3.5 1.3 0.2]
 [5.1 3.8 1.5 0.3]
 [5.5 2.5 4.  1.3]
 [4.7 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [6.7 3.  5.  1.7]
 [5.8 2.7 3.9 1.2]
 [5.  3.3 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [7.2 3.  5.8 1.6]
 [5.1 3.5 1.4 0.3]
 [5.4 3.9 1.7 0.4]
 [4.6 3.1 1.5 0.2]
 [6.2 3.4 5.4 2.3]
 [5.7 3.  4.2 1.2]
 [5.  2.3 3.3 1. ]
 [6.3 2.8 5.1 1.5]
 [5.6 3.  4.1 1.3]
 [6.3 2.7 4.9 1.8]
 [5.8 2.7 5.1 1.9]
 [7.7 2.8 6.7 2. ]
 [6.4 2.7 5.3 1.9]
 [6.7 3.3 5.7 2.1]
 [6.5 3.  5.8 2.2]
 [7.  3.2 4.7 1.4]
 [6.  2.2 5.  1.5]
 [5.7 4.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [6.2 2.2 4.5 1.5]
 [5.4 3.9 1.3 0.4]
 [5.  3.6 1.4 0.2]
 [6.3 2.5 4.9 1.5]
 [5.  3.  1.6 0.2]
 [6.1 2.6 5.6 1.4]
 [6.9 3.1 5.4 2.1]
 [5.2 4.1 1.5 0.1]
 [6.2 2.9 4.3 1.3]
 [6.5 2.8 4.6 1.5]
 [5.4 3.  4.5 

In [245]:
print("\n30% test data:")
print(X_test)
print(y_test)


30% test data:
[[5.  3.4 1.6 0.4]
 [6.6 3.  4.4 1.4]
 [6.6 2.9 4.6 1.3]
 [4.9 2.4 3.3 1. ]
 [5.  3.5 1.6 0.6]
 [7.6 3.  6.6 2.1]
 [7.4 2.8 6.1 1.9]
 [5.6 2.7 4.2 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 3.1 1.5 0.1]
 [4.6 3.6 1.  0.2]
 [5.  3.4 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [6.  3.  4.8 1.8]
 [6.3 2.9 5.6 1.8]
 [5.5 2.4 3.8 1.1]
 [6.8 3.  5.5 2.1]
 [6.1 3.  4.6 1.4]
 [6.  2.9 4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.  5.2 2.3]
 [6.9 3.1 4.9 1.5]
 [6.4 3.2 5.3 2.3]
 [5.7 2.5 5.  2. ]
 [4.3 3.  1.1 0.1]
 [6.7 3.1 4.4 1.4]
 [5.2 3.5 1.5 0.2]
 [5.7 2.8 4.5 1.3]
 [6.9 3.1 5.1 2.3]
 [5.1 3.4 1.5 0.2]
 [5.6 2.8 4.9 2. ]
 [6.8 2.8 4.8 1.4]
 [6.4 3.2 4.5 1.5]
 [5.8 2.7 5.1 1.9]
 [6.7 3.3 5.7 2.5]
 [7.7 2.6 6.9 2.3]
 [6.1 2.8 4.  1.3]
 [4.8 3.  1.4 0.1]
 [5.8 4.  1.2 0.2]
 [4.4 2.9 1.4 0.2]
 [5.7 2.8 4.1 1.3]
 [5.6 2.5 3.9 1.1]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [5.  3.5 1.3 0.3]]
['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-vers

In [251]:
print("shape of x train is",X_train.shape)
print("shape of x test is",X_test.shape)
print("shape of y train is",y_train.shape)
print("shape of y test is",y_test.shape)


shape of x train is (105, 4)
shape of x test is (45, 4)
shape of y train is (105,)
shape of y test is (45,)


In [252]:

knn = KNeighborsClassifier(n_neighbors=5)
#Train the model using the training sets
knn.fit(X_train, y_train)
#Predict the response for test dataset
print("Response for test dataset:")
y_pred = knn.predict(X_test)
print(y_pred)


Response for test dataset:
['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa']


In [237]:
print(y_test)

['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa']
